<a href="https://colab.research.google.com/github/naro-naro/Colab/blob/main/231027.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 중간고사 리뷰 3번
a = int(input ('첫번째 숫자 입력: '))
b = float(input ('en번째 숫자 입력: '))
# print('%d + %.1f = %.1f'%(a,b)) : 변수가 하나 모자라서 오류 발생


# 중간고사 리뷰 12번
num = [8,6,5,2,4]
num.sort(reverse=True)
print(num)


# 중간고사 리뷰 16번
# 튜플은 insert()사용이 불가능함


# 중간고사 리뷰 20번
inStr = 'Python_is_Fun!'
outStr=''
for i in range(0, len(inStr)):
    if i%2==0:
        outStr+=inStr[len(inStr)-(i+1)]
    else:
        outStr+='@'
print("원본 내용 --> Python_is_Fun!")
print("변경 내용 -->",outStr)

첫번째 숫자 입력: 20
en번째 숫자 입력: 10
[8, 6, 5, 4, 2]
원본 내용 --> Python_is_Fun!
변경 내용 --> !@u@_@i@n@h@y@


In [ ]:
# 중간고사 리뷰 서술 A번
fruitdb = []
fruitdb.append(['apple',1000,1])
print(f'fruitdb={fruitdb}')

fruitdb=[['apple', 1000, 1]]


In [ ]:
# 중간고사 리뷰 서술 A번
fruitdb = []
for i in range(3):
    name=input('과일이름 입력: ')
    cost=int(input('단가 입력: '))
    many=int(input('수량 입력: '))
    fruitdb.append([name, cost, many])
print(f'fruitdb={fruitdb}')

hap, count = 0,0
for i in range(len(fruitdb)):
    hap += fruitdb[i][1]*fruitdb[i][2]
    count += fruitdb[i][2]
avg=hap/count
print("구매한 모든 과일의 평균은 %.1f원"%(avg))

과일이름 입력: apple
단가 입력: 1000
수량 입력: 1
과일이름 입력: orange
단가 입력: 1500
수량 입력: 2
과일이름 입력: banana
단가 입력: 2000
수량 입력: 1
fruitdb=[['apple', 1000, 1], ['orange', 1500, 2], ['banana', 2000, 1]]
구매한 모든 과일의 평균은 1500.0원


In [ ]:
# 중간고사 리뷰 서술 B번
class You:
    def __init__(self):
        self.name=input("이름: ")
        self.age=int(input("나이: "))
    def show(self):
        print('='*10,'입력받은 학생정보','='*10)
        print('이름:',self.name,'나이:',self.age)

student=[]
for i in range(3):
    student.append(You())

for i in range(len(student)):
    student[i].show()

이름: 홍길동
나이: 20
이름: 수지
나이: 22
이름: 아이유
나이: 24
========== 입력받은 학생정보 ==========
이름: 홍길동 나이: 20
========== 입력받은 학생정보 ==========
이름: 수지 나이: 22
========== 입력받은 학생정보 ==========
이름: 아이유 나이: 24


# 객체지향 프로그래밍 - 빈도수

In [ ]:
# 빈도수를 구하는 프로그램

text = "AI! 나는 인공지능 로봇 입니다. 나는 'AI 로봇' 입니다."
print(text.split(' ')) # 리스트 형태로 출력

['AI!', '나는', '인공지능', '로봇', '입니다.', '나는', "'AI", "로봇'", '입니다.']


In [ ]:
# 빈도수
text = "AI! 나는 인공지능 로봇 입니다. 나는 'AI 로봇' 입니다."
text.split(' ')
print(text)

AI! 나는 인공지능 로봇 입니다. 나는 'AI 로봇' 입니다.


In [ ]:
# 빈도수 계산1

text = "AI! 나는 인공지능 로봇 입니다. 나는 'AI 로봇' 입니다."
def max_counts(text):
    counts = {} # 딕셔너리
    for i in text.split(' '): #Ai!, 나는, 인공지능, 로봇, 입니다., 나는, 'Ai, 로봇', 입니다.
        if i in counts:    # 딕셔너리에 이미 추가된 key라면 +1 (앞에서 이미 나왔다면 +!)
            counts[i] +=1
        else:    # 처음보는 글자면 counts에 key로 추가
            counts[i] = 1
    return counts

# max_counts(text)
print(max_counts(text))

{'AI!': 1, '나는': 2, '인공지능': 1, '로봇': 1, '입니다.': 2, "'AI": 1, "로봇'": 1}


In [ ]:
# 빈도수 계산2

text = "AI! 나는 인공지능 로봇 입니다. 나는 'AI 로봇' 입니다."

def max_counts(text):
    skips = ['.', '!', ',', "'", '"', ':', ';', '?']
    for ch in skips:
        text = text.replace(ch, '')
    counts = {}
    for i in text.split(' '):
        if i in counts:
            counts[i] += 1
        else:
            counts[i] = 1
    return counts

print(max_counts(text))

{'AI': 2, '나는': 2, '인공지능': 1, '로봇': 2, '입니다': 2}


In [ ]:
people = ['홍', '이', '김', '이', '이', '김']

def max_count(people):
    counts = {}
    for i in people:
        if i in counts:
            counts[i] += 1
        else:
            counts[i] = 1
    return counts

counts = max_count(people)

print(counts)
print(max(counts))
print(max(counts, key=counts.get)) #빈도수가 가장 높은 value

{'홍': 1, '이': 3, '김': 2}
홍
이


In [ ]:
people = ['홍', '이', '김', '이', '이', '김']

def max_count(people):
    counts = {}
    for i in people:
        if i in counts:
            counts[i] += 1
        else:
            counts[i] = 1
    return counts

counts = max_count(people)

print(counts)
print(max(counts))
print(max(counts, key=counts.get)) #빈도수가 가장 높은 value

print(max(counts.values()))
print(counts.items())
for name, count in counts.items():
    print(name, count)

{'홍': 1, '이': 3, '김': 2}
홍
이
3
dict_items([('홍', 1), ('이', 3), ('김', 2)])
홍 1
이 3
김 2


In [ ]:
people = ['홍', '홍', '김', '이', '홍', '김']

def max_count(people):
    counts = {}
    for i in people:
        if i in counts:
            counts[i] += 1
        else:
            counts[i] = 1
    return counts

counts=max_count(people)
first = []
max_num = max(counts.values())

for name, count in counts.items():
    print(name, ':', count,'번')
    if count == max_num:
        first.append(name)
print('1등:', first)

홍 : 3 번
김 : 2 번
이 : 1 번
1등: ['홍']


In [ ]:
nums = [1, 1, 1, 2, 2, 3, 2, 3, 3, 3, 1]

def max_count(nums):
    counts = {}
    for i in nums:
        if i in counts:
            counts[i] += 1
        else:
            counts[i] = 1
    return counts

counts = max_count(nums)
first = []
max_num = max(counts.values())

for name, count in counts.items():
    print(name, ':', count,'번')
    if count == max_num:
        first.append(name)
print('1등:', first)

1 : 4 번
2 : 3 번
3 : 4 번
1등: [1, 3]


# 넘파이 Numpy

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
a= np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
a= np.zeros(9)
print(a)
b=np.zeros((3,3))
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
a= np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
a= np.ones(9)
print(a)
b=np.ones((2,3))
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
b=np.ones((2,3,4))
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
b=np.full((2,3), 1.5)
print(b)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [ ]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.tri(4)
print(a)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [ ]:
a=np.arange(1, 21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
a=np.arange(1, 21,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
a=np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
a=np.logspace(np.log10(10), np.log10(100),5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [ ]:
a=np.random.random()
print(a)

0.22080885264370587


In [ ]:
a=np.random.randint(1,10)
print(a)

2


In [ ]:
a=np.random.randint(1,10,(4,4))
print(a)

[[2 6 2 6]
 [5 3 7 2]
 [9 4 2 8]
 [9 5 2 5]]


In [ ]:
randint_list=[]
for i in range(10000):
    a=np.random.randint(1,10)
    randint_list.append(a)

def max_count(nums):
    counts = {}
    for i in nums:
        if i in counts:
            counts[i] += 1
        else:
            counts[i] = 1
    return counts

counts = max_count(randint_list)
first = []
max_num = max(counts.values())

for name, count in counts.items():
    print(name, ':', count,'번')
    if count == max_num:
        first.append(name)
print('1등:', first)

1 : 1108 번
5 : 1142 번
7 : 1088 번
2 : 1130 번
4 : 1127 번
3 : 1101 번
8 : 1115 번
9 : 1121 번
6 : 1068 번
1등: [5]


In [ ]:
a1=np.arange(9)
print(a1)
print(a1[0])
print(a1[-1])
a1[0]=10
print(a1)

[0 1 2 3 4 5 6 7 8]
0
8
[10  1  2  3  4  5  6  7  8]


In [ ]:
a1=np.arange(9).reshape((3,3))
print(a1)
print(a1[0,1]) #0행 1열
print(a1[1,2]) #1행 2열
a1[0,0]=10 #0행 0열의 원소 변경
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
5
[[10  1  2]
 [ 3  4  5]
 [ 6  7  8]]


# 배열 슬라이싱

In [ ]:
a2 = np.arange(1,25).reshape((4,6))

print(a2)
print("-"*20)
print()

print(a2[1])
print()

print(a2[1:3,1:5]) #1행~2행, 1열~4열
print()

print(a2[2,:]) #인덱스 2인 요소 전부 다 출력
print()

print(a2[:3,:3])
print()

print(a2[2:,::-1]) # 역순으로
print()

print(a2[::-1,::-1])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
--------------------

[ 7  8  9 10 11 12]

[[ 8  9 10 11]
 [14 15 16 17]]

[13 14 15 16 17 18]

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]

[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]

[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


# 논리 인덱싱

In [ ]:
a = np.arange(11)
print(a)
print(a[a<5], end='\n\n')

print(a>=5)
five_up = (a>=5)
print(five_up)
print(a[five_up], end='\n\n')

divide_by_2 = a[a%2==0]
print(divide_by_2, end='\n\n')

divide_by_o = a[~(a%2==0)]    # divide_by_o = a[~(a%2!=0)]
print(divide_by_o)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]


[False False False False False  True  True  True  True  True  True]
[False False False False False  True  True  True  True  True  True]
[ 5  6  7  8  9 10]


[ 0  2  4  6  8 10]


[1 3 5 7 9]


In [ ]:
# 논리 연산자 사용
c= a[(a>5)&(a<11)]
print(c)

d=a[(a>9)|(a<5)]
print(d)

e=a[~(a%3==0)]
print(e)

[ 6  7  8  9 10]
[ 0  1  2  3  4 10]
[ 1  2  4  5  7  8 10]


In [ ]:
# 산술연산
a=np.arange(1,11)
b=np.arange(1,11)

print(a+b)
print(np.add(a,b))
print()

print(a-b)
print(np.subtract(a,b))
print()

print(a*b)
print(np.multiply(a,b))
print()

print(a/b)
print(np.divide(a,b))


[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]

[  1   4   9  16  25  36  49  64  81 100]
[  1   4   9  16  25  36  49  64  81 100]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# 제곱근
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


# 집계함수

# 브로드캐스팅 연산

#벡터 연산

In [ ]:
# 브로드캐스팅
import numpy as np
x= np.array([1,2,3,4,5])
y=1
print(x+y)

[2 3 4 5 6]
