<a href="https://colab.research.google.com/github/naro-naro/Colab/blob/main/231103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 전치행렬 : 행과 열 바꾸기
# 대각선을 기준으로 행렬 뒤집어짐
import numpy as np
a=np.random.randint(1,10,(3,3)) # 1~9의 랜덤 : 10은 안나옴
print(a)
print()
print(a.T)

[[4 6 1]
 [1 9 8]
 [3 6 7]]

[[4 1 3]
 [6 9 6]
 [1 8 7]]


In [ ]:
# 배열을 1차원 배열로 반환
a=np.array([[1,2,3],[4,5,6]])
print(a)
a.ravel()
b=a.ravel()
print(b)
b[0]=10
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]


In [ ]:
# 배열 속성 정보
arr=np.arange(1,6)
print(arr)
print("ndim:", arr.ndim) # 차원
print("shape:", arr.shape) # 모양 (1차원 배열인데 요소가 5개)
print("dtype:", arr.dtype)
print("size:", arr.size)
print("itemsize:", arr.itemsize)
print("nbytes:", arr.nbytes)

[1 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40


In [ ]:
# reshape() : 모양바꾸기
list_data=[1,2,3,4,5,6]
list_data.reshape(3,2)
# numpyarray로 변환하지 않으면 오류 발생

AttributeError: ignored

In [ ]:
# reshape() : 모양바꾸기
import numpy as np
list_data=[1,2,3,4,5,6]
data=np.array(list_data)
print(type(data))
print(data.reshape(3,2)) # 3*2배열로 형태 변환
print(list_data)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[1, 2, 3, 4, 5, 6]


In [ ]:
# .resize() : shape을 변경하는 과정에서 배열 요소 수를 줄이거나 늘림
x=np.arange(20)
print(x)
y=np.resize(x,(4,5))
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# 요소 수가 더 많은 경우 : 요소추가
z=np.resize(x,(5,5))
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [ ]:
# 요소 수가 더 적은 경우 : 요소삭제
zz=np.resize(x,(3,3))
print(zz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 요소 추가
* append()
*insert()

In [ ]:
# append: 배열의 끝에 값을 추가
x = np.arange(3)
y =np.append(x,5)
print(y)

[0 1 2 5]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([7,8,9])
c = np.append(a,b)
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9]])
c = np.append(a,b, axis=0)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c = np.append(a,b, axis=0)
print(c)
print()

d = np.append(a,b, axis=1)
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# insert() : 주어진 축에 대해 주어진 인덱스 앞에 값을 삽입
# 값 추가 - 1차원 배열
a = np.array([1,2,3])
b = np.insert(a,1,5) # a라는 배열에 1번 인덱스 자리에 값 5를 추가
print(a)
print(b)

[1 2 3]
[1 5 2 3]


In [ ]:
# 값 추가 - 2차원 배열
a = np.array([[1,1],[2,2],[3,3]])
b = np.insert(a,1,5) # a라는 배열에 1번 인덱스 자리에 값 5를 추가
print(a)
print(b)

[[1 1]
 [2 2]
 [3 3]]
[1 5 1 2 2 3 3]


In [ ]:
# 값 추가 - 2차원 배열
# 축 지정
a = np.array([[1,1],[2,2],[3,3]])
b = np.insert(a,1,5, axis=0) # a라는 배열에 1번 인덱스 자리에 값 5를 추가
print(a)
print()
print(b)

[[1 1]
 [2 2]
 [3 3]]
[[1 1]
 [5 5]
 [2 2]
 [3 3]]


In [ ]:
c = np.insert(a,1,5, axis=1) # a라는 배열에 1번 인덱스 자리에 값 5를 추가
print(c)

[[1 5 1]
 [2 5 2]
 [3 5 3]]


# 요소 삭제
* delete()

In [ ]:
# delete() : 배열 요소 삭제
a= np.arange(12).reshape(3,4)
print(a, end='\n\n')
print(np.delete(a,5), end='\n\n') # a배열에서 값5를 삭제해 1차원으로 출력

b= np.arange(12).reshape(3,4)
print(np.delete(b,1, axis=0), end='\n\n') # b배열에서 1번째 행을 삭제해 출력

c= np.arange(12).reshape(3,4)
print(np.delete(c,1, axis=1), end='\n\n') # b배열에서 1번째 열을 삭제해 출력

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[ 0  1  2  3  4  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 8  9 10 11]]

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]



# 배열 연결 : concatenate()

In [ ]:
# concatenate() : 두 배열을 연결하여 반환
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
arr1 = np.concatenate((a,b))
print(arr1, end='\n\n')
arr2 = np.concatenate((a,b),axis=0)
arr3 = np.concatenate((a,b),axis=1)
print(arr2)
print(arr3)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


# 추가
* 행 추가 : vstack
* 열 추가 : hstack

In [ ]:
# vstack() : 행 추가
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
# hstack() : 열 추가
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


# 분리
* 행 분리 : vsplit
* 열 분리 : hsplit

In [ ]:
# hsplit(): 행 방향으로 분리
a = np.arange(16).reshape(4,4)
a_hsplit = np.hsplit(a,2)
print(a, end='\n\n')
print(a_hsplit)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [ ]:
# hsplit(): 행 방향으로 분리
a = np.arange(16).reshape(4,4)
a_hsplit = np.hsplit(a,3) # 3개로 쪼개면 차원이 같지 않아 오류 발생
print(a)
print(a_hsplit)

ValueError: ignored

In [ ]:
# vsplit(): 열 방향으로 분리
a = np.arange(16).reshape(4,4)
a_vsplit = np.vsplit(a,2)
print(a, end='\n\n')
print(a_vsplit)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# 4단원 연습문제

In [ ]:
# 문제1
arr = np.arange(1,11)
print(arr)
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("dtype:", arr.dtype)
print("size:", arr.size)

[ 1  2  3  4  5  6  7  8  9 10]
ndim: 1
shape: (10,)
dtype: int64
size: 10


In [ ]:
# 문제2(1)
# 1)
a = np.arange(10,50)
a= a[::-1] #역순으로
print(a, end='\n\n')

# 2)
import random
import numpy as np
a= np.random.random((10,10))
print(a)
max= a.max()
min=a.min()
print(max, min, end='\n\n')

# 3)
a=np.arange(9).reshape(3,3)
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]

[[0.25691831 0.61796441 0.92543343 0.32882559 0.96762851 0.42767512
  0.02741082 0.66564704 0.96513274 0.60893773]
 [0.43163219 0.84151859 0.56535774 0.55129524 0.02782314 0.31026077
  0.46323196 0.5465328  0.93782041 0.35552698]
 [0.95662415 0.7771527  0.08560245 0.31390236 0.88920382 0.63552381
  0.32951401 0.72551264 0.87205296 0.28530014]
 [0.9394831  0.63343509 0.52857855 0.80738727 0.89774875 0.14177902
  0.78424507 0.80784141 0.31863095 0.18332594]
 [0.65716389 0.09351325 0.12160377 0.3779776  0.43028874 0.49080881
  0.03098526 0.61938955 0.76684815 0.68828841]
 [0.51335613 0.81972483 0.58316164 0.98716337 0.59663022 0.55415226
  0.95320356 0.30314106 0.96685943 0.04725708]
 [0.95702464 0.46672363 0.59758586 0.83137213 0.46746435 0.46404669
  0.44575573 0.8356042  0.89164551 0.90637642]
 [0.25295013 0.17072692 0.04859067 0.05398015 0.68370023 0.93366432
  0

In [ ]:
# 문제2(2)
# 4-1)
a=np.arange(1,25).reshape(4,6)
print(a, end='\n\n')

# 4-2)
print(a[1:3,1:5], end='\n\n')

# 4-3)
print(a[2:,::-1], end='\n\n')

# 4-4)
a[a%2==0]

# 4-5)
result=a[(a>=10)&(a<=20)]


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

[[ 8  9 10 11]
 [14 15 16 17]]

[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]



array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# 문제3
a=np.arange(1,21)
print('마지막원소:',a[-1])
print('원소합:',a.sum())
print('원소평균:',a.mean())
new_a = a.reshape(4,5)
print(new_a)

마지막원소: 20
원소합: 210
원소평균: 10.5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
# 문제4
sal = [200,150,180,220,250]
new_sal = np.array(sal,dtype='float64')*1.5
print('인상된 금액:',new_sal)
avg_sal = np.mean(new_sal)
print('평균 금액:',avg_sal)
result = new_sal >= avg_sal
print('평균 이상인 원소:',new_sal[result])
print('평균 이상인 원소의 개수:',len(new_sal))

인상된 금액: [300. 225. 270. 330. 375.]
평균 금액: 300.0
평균 이상인 원소: [300. 330. 375.]
평균 이상인 원소의 개수: 5


# Pandas 라이브러리
* 자료형
** Series : 열이 1개
** DataFrame : 열이 여러개

In [ ]:
import pandas as pd
score = pd.Series([95,90,85,90,95])
score

0    95
1    90
2    85
3    90
4    95
dtype: int64

In [ ]:
import pandas as pd
score = pd.Series([95,90,85,90,95], index=['홍길동','아이유','수지','이강인','제시'])
score

홍길동    95
아이유    90
수지     85
이강인    90
제시     95
dtype: int64

In [ ]:
import pandas as pd
import numpy as np
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
import pandas as pd
import numpy as np
arr = np.arange(12)
arr = np.arange(12).reshape(4,3)
df = pd.DataFrame(arr)
print(arr, end="\n\n")
print(df)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11


In [ ]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
df = pd.DataFrame(arr)
print(df)

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11


In [ ]:
# DataFrame 만들기, 딕셔너리 구조 이용
df = pd.DataFrame({'name':['아이유','수지','이강인'],
                   'score':[95,90,85],
                   'dept':['com','eng','math']})
df
# 딕셔터리의 키로는 인덱스를 쓸 수 없다 : 변경가능해서
# 튜플은 변경 불가능해서 쓸 수 있다

name  score  dept
0  아이유     95   com
1   수지     90   eng
2  이강인     85  math

# CSV 파일

* csv 파일을 메모장에 드래그해보면,,

* Brand,Color,price
*Samsung,Black,100
*LG,Gold,70
*Apple,Silver,150
*Apple,Gray,120
* 맨앞줄 : 인덱스

In [ ]:
filename = '/content/drive/MyDrive/Colab Notebooks/2023-2 언분프/mobile.csv'
import pandas as pd
df = pd.read_csv(filename)
df

Brand   Color  price
0  Samsung   Black    100
1       LG    Gold     70
2    Apple  Silver    150
3    Apple    Gray    120